### ISSUE TITLE
Undefined property: stdClass::$IdConhecimento 

### ISSUE THREAD

**Issue by ricardocechinel** [softr/visualset-vipp#1]
Notice: Undefined property: stdClass::$IdConhecimento in C:\xampp\htdocs\visualset\vendor\softr\visualset-vipp\src\Api\Rastreio.php on line 39
bool(false)

**Comment by aldoanizio** [comment]
Obrigado por reportar o erro. Lancei uma correção com umas pequenas melhorias.
